name: plan
on:
  pull_request:
  push:
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform plan
  plan-slack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slack
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform plan
  plan-slack-beta:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slack-beta
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform plan
